import { DemoReelItem } from '@trustlens/shared';

/**
 * TrustLens Demo Reels Configuration
 * 
 * NOTE FOR FUTURE PRODUCTION DEPLOYMENT:
 * The final 10 real evaluation videos have NOT yet been provided by the user.
 * This configuration layer isolates video metadata and file references from the
 * verification engine and UI. When the final 10 real video files are provided,
 * simply update this configuration array and place the corresponding video assets
 * into `server/demo-videos/` and `client/public/demo-videos/`.
 */
export const DEMO_REELS_CONFIG: DemoReelItem[] = [
  {
    id: 'moon-landing',
    title: 'Apollo 11 Lunar Landing Historical Footage',
    description: 'Archival video showing Apollo 11 lunar module landing on the Moon with astronaut commentary.',
    claimedContext: 'Apollo 11 lunar landing in July 1969 Neil Armstrong and Buzz Aldrin.',
    duration: 8,
    category: 'Historical Science',
    videoUrl: '/demo-videos/moon-landing.mp4',
    thumbnailUrl: '',
    sourceFilename: 'moon-landing.mp4',
  },
  {
    id: 'wildfire-recycled',
    title: 'Devastating California Wildfire 2026',
    description: 'Dramatic blaze footage circulated on social media claiming to be a wildfire in California in 2026.',
    claimedContext: 'Breaking: Massive California wildfire spreading in October 2026.',
    duration: 6,
    category: 'Context Recycling',
    videoUrl: '/demo-videos/wildfire-recycled.mp4',
    thumbnailUrl: '',
    sourceFilename: 'wildfire-recycled.mp4',
  },
  {
    id: 'fusion-ignition',
    title: 'National Ignition Facility Net Energy Gain',
    description: 'Laboratory report detailing controlled nuclear fusion experiment yielding 3.15 MJ output.',
    claimedContext: 'National Ignition Facility achieves net energy gain in nuclear fusion experiment.',
    duration: 10,
    category: 'Scientific Breakthrough',
    videoUrl: '/demo-videos/fusion-ignition.mp4',
    thumbnailUrl: '',
    sourceFilename: 'fusion-ignition.mp4',
  },
  {
    id: 'deep-field-jwst',
    title: 'James Webb Space Telescope First Deep Field',
    description: 'NASA press release video displaying galaxy cluster SMACS 0723 captured in infrared.',
    claimedContext: 'NASA James Webb Space Telescope releases deepest infrared image of the early universe.',
    duration: 8,
    category: 'Astronomy',
    videoUrl: '/demo-videos/deep-field-jwst.mp4',
    thumbnailUrl: '',
    sourceFilename: 'deep-field-jwst.mp4',
  },
  {
    id: 'wire-transfer-scam',
    title: 'CEO Video Urgent Wire Transfer Demand',
    description: 'Video message purporting to be from corporate executive ordering immediate treasury funds transfer.',
    claimedContext: 'Urgent emergency executive authorization for overseas account transfer.',
    duration: 5,
    category: 'Financial Social Engineering',
    videoUrl: '/demo-videos/wire-transfer-scam.mp4',
    thumbnailUrl: '',
    sourceFilename: 'wire-transfer-scam.mp4',
  },
  {
    id: 'mars-curiosity',
    title: 'Curiosity Rover Mount Sharp High-Resolution Panorama',
    description: 'Curiosity rover mast camera scanning clay-bearing geological units on lower Mount Sharp.',
    claimedContext: 'NASA Curiosity Rover scientific imaging on Mount Sharp Mars.',
    duration: 7,
    category: 'Planetary Science',
    videoUrl: '/demo-videos/mars-curiosity.mp4',
    thumbnailUrl: '',
    sourceFilename: 'mars-curiosity.mp4',
  },
  {
    id: 'venice-flooding',
    title: 'Acqua Alta Venice High Tide Flood',
    description: 'Video showing deep tidal flooding across Piazza San Marco in Venice.',
    claimedContext: 'Historic Venice lagoon high tide acqua alta floodwaters.',
    duration: 7,
    category: 'Climate & Extreme Weather',
    videoUrl: '/demo-videos/venice-flooding.mp4',
    thumbnailUrl: '',
    sourceFilename: 'venice-flooding.mp4',
  },
  {
    id: 'miracle-herb-cure',
    title: 'Miracle Herb Cures All Chronic Illnesses',
    description: 'Viral wellness reel asserting that a rare Himalayan herbal infusion permanently cures diabetes and cancer.',
    claimedContext: 'Miracle herb tea proven by doctors to cure diabetes and cancer without medicine.',
    duration: 8,
    category: 'Health Misinformation',
    videoUrl: '/demo-videos/miracle-herb-cure.mp4',
    thumbnailUrl: '',
    sourceFilename: 'miracle-herb-cure.mp4',
  },
  {
    id: 'sprint-world-record',
    title: 'Usain Bolt 9.58s 100m Berlin World Record',
    description: 'Archival broadcast recording of the men 100-meter final at the 2009 World Athletics Championships in Berlin.',
    claimedContext: 'Usain Bolt sets world record of 9.58 seconds in Berlin 2009.',
    duration: 6,
    category: 'Sports History',
    videoUrl: '/demo-videos/sprint-world-record.mp4',
    thumbnailUrl: '',
    sourceFilename: 'sprint-world-record.mp4',
  },
  {
    id: 'protest-crowd',
    title: 'Massive Demonstration Crowd in City Center',
    description: 'Aerial drone footage of thousands assembling along metropolitan avenues.',
    claimedContext: 'Massive protest march against economic reform downtown.',
    duration: 8,
    category: 'Breaking News Attribution',
    videoUrl: '/demo-videos/protest-crowd.mp4',
    thumbnailUrl: '',
    sourceFilename: 'protest-crowd.mp4',
  },
];
